name: Auto Commit
on:
  push:
    branches:
      - main # Execute apenas em pushes para a branch main

# Permissões necessárias para o workflow
permissions:
  contents: write # Permite que a action faça commit no seu repositório

jobs:
  auto_commit_job:
    runs-on: ubuntu-latest
    steps:
      # 1. Faz o checkout do seu repositório para que o workflow possa acessá-lo
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      # 2. Passo de exemplo: Modifique ou crie um arquivo
      #    Este passo simula a mudança que você quer commitar.
      - name: Modificar arquivo de data
        run: |
          echo "Este arquivo foi atualizado pela última vez em: $(date)" > last-updated.txt

      # 3. Use a action para fazer o commit
      - name: Fazer Commit das Mudanças
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Mensagem do commit
          commit_message: 'ci: Atualiza arquivo com a data mais recente'

          # Opcional: Autor do commit (padrão é o bot do GitHub Actions)
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com

          # Opcional: Adiciona todos os arquivos novos e modificados
          # file_pattern: '*.txt' # Você pode especificar padrões, ex: apenas arquivos .txt
