# Nome do seu workflow
name: Deploy to Vercel Production

# Gatilhos
on:
  push:
    branches:
      - master # Ou 'master', se for o seu branch principal
    if: github.actor != 'github-actions[bot]' # Adicione esta condição para evitar loops (se houver auto-commit)

  workflow_dispatch:

# Jobs
jobs:
  deploy:
    runs-on: ubuntu-latest

    # Variáveis de ambiente para o job
    env:
      GITHUB_ID: ${{ secrets.CLIENT_ID }}
      GITHUB_SECRET: ${{ secrets.CLIENT_SECRET }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      NEXTAUTH_SECRET: ${{ secrets.SECRET }} # Ou SECRET, dependendo do seu código
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Passo 2: Configura o ambiente Node.js e instala as dependências
      - name: Setup Node.js and Install Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a versão do Node.js que seu projeto precisa
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm install



      # --- ETAPA DE TESTES E VALIDAÇÃO ---

      # Passo 3: Roda o Linter
      - name: Run Linter for Code Quality
        run: npx eslint . --ext .js --max-warnings 0
      
      # Passo 4: Validação do HTML com o W3C (USANDO AÇÃO CORRIGIDA)
      # ATENÇÃO: Se seu projeto é Next.js e não tem um index.html estático na raiz,
      # este passo pode não ser relevante ou precisar de um caminho diferente.
      # Usando uma ação mais atualizada e popular para validação HTML.
      - name: Validate HTML with W3C
        with:
          url: https://eng-soft-black.vercel.app/ # Valida o HTML do seu site já deployado
          # Ou, se quiser validar um arquivo local:
          # path: index.html 




      # --- ETAPA DE DEPLOY ---

      # Passo 5: Faz o deploy para Vercel (USANDO AÇÃO CORRIGIDA)
      - name: Deploy Project to Vercel
        uses: main # Versão atualizada da Vercel Action.
                                # Você pode usar 'main' para a última versão beta/desenvolvimento
                                # ou verificar a documentação oficial da Vercel para a versão estável mais recente.
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          org-id: ${{ secrets.VERCEL_ORG_ID }}
          project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod' 



      # --- ETAPA DE TESTE PÓS-DEPLOY ---

      # Passo 6: Verifica links quebrados no site em produção
      - name: Check for broken links
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: "https://eng-soft-black.vercel.app/" # Verifique a URL do seu site
